Feature/docs 2642 sbfa and user attribution in api sessions
wallarm/product-documentation pull request #1412
Opened 2024-11-27 14:07 UTC by MaximBashurov

2024-12-13 03:44 UTC, slega requested changes

2024-12-13 03:44 UTC, slega commented on docs/4.10/api-discovery/overview.md
> +Once tags are assigned, you can filter your endpoints by flow to regularly check them for vulnerabilities or breaches.
We need screenshots here to demonstrate to how do that in the interface.

2024-12-13 03:44 UTC, slega commented on docs/4.10/api-discovery/overview.md
> +Once tags are assigned, you can filter your endpoints by flow to regularly check them for vulnerabilities or breaches.
There two different terms for the same things: 'tags' and 'marking'. I propose sticking to 'tags'.

2024-12-13 03:44 UTC, slega commented on docs/4.10/api-discovery/overview.md
> +API Discovery allows [marking](sbf.md) specific endpoints as the key ones for some sensitive business flows, such as:
As a pre-phrase, we need to explain the value of this i.e. a user might be interested in marking endpoints. I propose rephrasing this:
With the Sensitive business flow capability, API Discovery can identify endpoint which are critical to specific business flows and functions, such: authentication, account management, billing, and similar critical capabilities.

Once endpoints are assigned with the sensitive business flow tags, it becomes possible to filter all discovered endpoint by a specific business flow which makes it easier on protecting the most critical business capabilities.

2024-12-13 03:44 UTC, slega commented on docs/4.8/api-discovery/overview.md
> +
Ditto: docs/4.10/api-discovery/overview.md .

2024-12-13 03:44 UTC, slega commented on docs/latest/api-discovery/overview.md
> +
Ditto: docs/4.10/api-discovery/overview.md .

2024-12-13 03:44 UTC, slega commented on docs/latest/api-discovery/sbf.md
> +Wallarm's [API Discovery](overview.md) automatically marks specific endpoints as the key ones for some sensitive business flows, such as authentication or account management, billing or SMS gateways
tags, not marks

2024-12-13 03:44 UTC, slega commented on docs/latest/api-discovery/sbf.md
> +Wallarm's [API Discovery](overview.md) automatically marks specific endpoints as the key ones for some sensitive business flows, such as authentication or account management, billing or SMS gateways
Please rephrase this line to focus the reader on the business value of this capability.

2024-12-13 03:44 UTC, slega commented on docs/latest/api-discovery/sbf.md
> +The abuse of the sensitive business flows is ranked six ([API6](https://owasp.org/API-Security/editions/2023/en/0xa6-unrestricted-access-to-sensitive-business-flows/)) among OWASP API Top 10 risks. W
fluency: The abuse of sensitive business flows ranks sixth among the OWASP API Top 10 risks.

2024-12-13 03:44 UTC, slega commented on docs/latest/api-discovery/sbf.md
> +## Addressed issues
We need to change that title to illustrate what we are actually talking about here. Something about the addressed problem itself e.g. Importance of protecting the sensitive business flows or similar.

2024-12-13 03:44 UTC, slega commented on docs/latest/api-discovery/sbf.md
> +The abuse of the sensitive business flows is ranked six ([API6](https://owasp.org/API-Security/editions/2023/en/0xa6-unrestricted-access-to-sensitive-business-flows/)) among OWASP API Top 10 risks. W
Wallarm allows clearly identify the endpoints tied to such flows to: > Protecting these sensitive business flows ensures business continuity, prevents leaking of sensitive data, reputation risks, and financial damage.

WIth the Sensitive business flows capability, Wallarm highlights health of the business-critical functions and helps swiftly and easily to:...

2024-12-13 03:44 UTC, slega commented on docs/latest/api-discovery/sbf.md
> +* Easily produce audit trails and evidence of data protection measures.
Flip the structure of these sentences. Currently it goes like: <doing something> <so that outcome>, reshaping to <get outcome> <by going something> makes it much more effective. Compare:
"Drink our coffee so that you can work faster" vs. "Work faster with our coffee."

2024-12-13 03:44 UTC, slega commented on docs/latest/api-discovery/sbf.md
> +On finding a new endpoint, API Discovery automatically checks if it potentially belongs to one or several sensitive business flows:
On discovering a new endpoint, API Discovery automatically checks whether it potentially belongs to one or more sensitive business flows

2024-12-13 03:44 UTC, slega commented on docs/latest/api-discovery/sbf.md
> +
Explain the capability first: it is automatic >> you don't need to spend your precious time on manually tagging the endpoints, it work OOTB like magic.

2024-12-13 03:44 UTC, slega commented on docs/latest/api-discovery/sbf.md
> +Automatic checking is performed based on the keywords from the endpoint URL, for example, `payment`, `subscription` `purchase`, etc. for the **Billing** flow or `auth`, `token`, `login`, etc. for **A
Quite difficult to read, I would rewrite this:  Automatic checks are conducted using keywords from the endpoint URL. For example, keywords like payment, subscription, or purchase automatically associate the endpoint with the Billing flow, while keywords such as auth, token, or login link it to the Authentication flow. If matches are detected, the endpoint is automatically assigned to the appropriate flow

2024-12-13 03:44 UTC, slega commented on docs/latest/api-discovery/sbf.md
> +If necessary, later you can manually adjust the list of assigned business flows as described in the section below.
The automatics tagging discovers most of the sensitive business flows. However, it is also possible to customize this capability to adjust it to specific business needs of your company.

2024-12-13 03:44 UTC, slega commented on docs/latest/api-discovery/sbf.md
> +## Marking endpoints manually
Focus on the customization and adjusting the capability to business needs of a customer, not something 'manual'

2024-12-13 03:44 UTC, slega commented on docs/latest/api-discovery/sbf.md
> +Wallarm's [API Sessions](../api-sessions/overview.md) group requests of your applications' traffic into user sessions. If some of these requests target the endpoints that in API Discovery were marked
> group requests of your applications' traffic into user sessions.

So then what? We need to start with business value and then explain how Wallarm helps to achieve that with this capability.

2024-12-13 03:44 UTC, slega commented on docs/latest/api-discovery/sbf.md
> +To adjust the results of [automatic marking](#automatic-marking), you can manually edit the list of sensitive business flow the endpoint belongs to. You can also manually mark endpoints that do not d
Marking > tagging, manual > customization, stars with business value. The ability to customize == you can configure the solution in a way it fits our specific organization.

2024-12-13 03:44 UTC, slega commented on docs/latest/api-discovery/sbf.md
> +## Filtering by business flow
business flow or sensitive business flow ?

2024-12-13 03:44 UTC, slega commented on docs/latest/api-discovery/sbf.md
> +Once endpoints are marked with the business flow tags, you can quickly get the list of endpoints belonging to specific business flow to analyze their current state and data.
marked > tagged. 

> you can quickly get the list of endpoints belonging to specific business flow to analyze their current state and data.
Put value first: You can analyze risks associated with ... by .....

2024-12-13 03:44 UTC, slega commented on docs/latest/api-discovery/sbf.md
> +To do that, use the **Business flow** filter.
Remove that by using the above formula

2024-12-17 08:39 UTC, MaximBashurov commented on docs/latest/api-discovery/sbf.md
> +To adjust the results of [automatic marking](#automatic-marking), you can manually edit the list of sensitive business flow the endpoint belongs to. You can also manually mark endpoints that do not d
Marking > tagging - ok
Business value in subsections - it is extra, we already mentioned in in intro.
We do not customize anything here, we manually adjust the results of automatic identification.

2025-01-06 13:25 UTC, MaximBashurov commented on docs/latest/api-discovery/sbf.md
> +## Addressed issues
I think that the "Addressed issues" title provides a clear understanding of what we are talking about. + this is used in other places of the docs similarly.

2025-01-17 13:26 UTC, slega approved these changes

2025-01-23 20:18 UTC, merged